export function action(message: any): void;
export function success(message: any): void;
export function error(message: any): void;
export function warn(message: any): void;
export function info(message: any): void;
export function header(message: any): void;
export function summary(succeeded: any, failed: any): void;
export function footer(message: any): void;
export function progress(pct: any, current: any, total: any, detail: any): void;
export function fail(message: any): void;
export function outputPath(filePath: any): void;
export function failedList(items: any): void;
